### ISSUE TITLE
cd on OS X has no effect(?)

### ISSUE THREAD

**Issue by mherrmann** [jamesob/desk#1]
Hi,

thanks for sharing the project; it sounds like a useful idea!

I installed desk 0.1.1 and put the following in `~/.desk/desks/app.sh`:

    # app.sh
    # 
    # Description: desk for doing work on my app
    # 
    
    cd /Users/michael/dev/app

`desk list` shows:

    app - desk for doing work on my app

But the `cd` in my desk definition has no effect:

    herrMBP:~ michael$ desk . app
    bash-3.2$ pwd
    /Users/michael

I would have expected the last line to read `/Users/michael/dev/app` (as per the cd command in my desk).

Am I doing something wrong?

**Comment by jasper-lyons** [comment]
I'm experiencing the same issue unfortunately.

**Comment by Green-Sky** [comment]
didn't work on my linux box either but i fixed it by adding:
```
if [[ $DESK_ENV ]]; then
    . $DESK_ENV
fi
```

to my .bashrc

**Comment by jamesob** [comment]
Ah yeah, my apologies. That's a crucial part of the installation I forgot to include. :)

I'll file a PR and reference this issue.

**Comment by Green-Sky** [comment]
:+1:

**Comment by andreimarcu** [comment]
Same here, thanks!

**Comment by jamesob** [comment]
Sorry about that, folks!
