### ISSUE TITLE
using a custom desks directory makes `desk` not work properly

### ISSUE THREAD

**Issue by MrMitch** [jamesob/desk#11]
I tried to use a custom dir to store my desks so that i can version it using git and push it to my git server, but `desk` behaves quite weirdly.
```
mitch@pc$ desk ls
No desk dir! Run 'desk init'.
mitch@pc$ ls /home/mitch/Workspace/desks/
dash.sh  rdcli.sh  symfony.sh  wp.sh
mitch@pc$ desk init
Desk dir already exists at /home/mitch/Workspace/desks
```

**Comment by MrMitch** [comment]
making the `~/.desk/desks` folder a symlink to my custom folder doesn't solve the problem

**Comment by jamesob** [comment]
Hey @MrMitch, sorr about that. Do you have `DESK_DIR=/home/mitch/Workspace/desks/` somewhere in your environment?

**Comment by tompaton** [comment]
I think you want DESK_DESKS_DIR=/home/mitch/Workspace/desks/

I was about to submit a pull request that allows ~/.desk/desks to be replaced with a symlink before I found that option.  (changing all instances of $DESKS to $DESKS/ worked form me in bash to force a symlink to be treated as a dir.)

**Comment by jamesob** [comment]
I'm not able to recreate on Ubuntu 14.04; I tried both a symlink (which is my current setup) and a custom path with `export DESK_DIR=/some/path` set in my `~/.zshrc`. 

@MrMitch can you give me more information about your environment?

**Comment by MrMitch** [comment]
I'm on Ubuntu 15.10 updated from a 15.04. 
I'll try and reinstall `desk` tomorrow. Maybe it has something to do with the way I defined`$DESK_DIR` variable ? I added `export DESK_DIR=/home/mitch/Workspace/desks` to my `.bashrc`.

**Comment by tompaton** [comment]
From what I can tell, `$DESK_DIR` should contain the "desks" directory, i.e. it defaults to `~/.desk`, in your case you should be using: `export DESK_DIR=/home/mitch/Workspace/`

But as I mentioned above, it'll make more sense to point directly to your custom folder using: `export DESK_DESKS_DIR=/home/mitch/Workspace/desks`

**Comment by jamesob** [comment]
I think we're safe closing this out, no?
