### ISSUE TITLE
Tab completions

### ISSUE THREAD

**Issue by rnewton** [jamesob/desk#17]
Hey @jamesob, I mentioned I'd make a list of the things I've got planned for my wrapper that would fit in better upstream. First one is tab completing names of the deskfiles you have. 

```
$ desk . som[Tab]
$ desk . some_desk_that_I_didnt_want_to_type_out
```

**Comment by jamesob** [comment]
Absolutely; this and PS1 modding are probably the two highest on my list right now.

**Comment by jamesob** [comment]
Related, see https://github.com/robbyrussell/oh-my-zsh/pull/4577 for oh-my-zsh.

**Comment by jamesob** [comment]
This is now in `master` for both zsh and bash. Let me know if anything doesn't work for you, @rnewton.
