### ISSUE TITLE
Symlink doesn't seem to work?

### ISSUE THREAD

**Issue by mungler** [jamesob/desk#34]
Tried symlinking my .desk folder to Dropbox, but Desk complains "No desk dir! Run 'desk init'."

I think this line won't match a symlink, only a real dir: https://github.com/jamesob/desk/blob/master/desk#L101

**Comment by jamesob** [comment]
Hmm... In the test script, we actually test this case explicitly: https://github.com/jamesob/desk/blob/master/test/run_tests.sh#L44

Your platform may differ from the Docker environment, though. What OS and shell are you running on?

**Comment by mungler** [comment]
OS X 10.11.1, default installed shell (bash)

**Comment by jamesob** [comment]
I'm unable to repro on Ubuntu 14.04:

```
 $ ls -lah ~/.desk
lrwxrwxrwx 1 job job 32 Oct 28 10:33 /home/job/.desk -> /home/job/Dropbox/code/desk_conf
 $ bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 $ [ ! -d "/home/job/.desk/" ] && echo "uhoh"
 $ 
```

I've got an OS X machine at home I'll try with tonight.

**Comment by mungler** [comment]
Hmm, interesting:

```
rory@Eddie:~ $ ls -lah ~/.desk
lrwxr-xr-x  1 rory  staff    33B 16 Nov 14:25 /Users/rory/.desk -> /Users/rory/Dropbox/dotfiles/desk
rory@Eddie:~ $ bash --version
GNU bash, version 4.3.39(1)-release (x86_64-apple-darwin14.4.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
rory@Eddie:~ $ [ ! -d "/Users/rory/.desk" ] && echo "uh oh"
rory@Eddie:~ $ 
```

**Comment by jamesob** [comment]
Could it be that you've got either `DESK_DIR` or `DESK_DESKS_DIR` set to some path that may not exist?

**Comment by jamesob** [comment]
@mungler I'd try modifying the script to see if you can get it to work, then we'll work backwards from there. I'll try to repro tonight.
