### ISSUE TITLE
Add tag for github release

### ISSUE THREAD

**Issue by cades** [jamesob/desk#4]
Hi @jamesob ,

thanks for your work, this is cool!

I want to submit a formula to homebrew, but found it requires version number in download url.

currently we can access tarball via `https://github.com/jamesob/desk/archive/master.tar.gz`.
and if we have a release, we can access tarball via `https://github.com/jamesob/desk/releases/download/1.0/desk-1.0.tar.gz`

 Could you add tag (and github release)?

**Comment by jamesob** [comment]
Hey, @cades. Thanks so much for working on the homebrew formula. I've created releaes v0.1.0, which should be accessible at https://github.com/jamesob/desk/archive/v0.1.0.zip.

Let me know if you hit any other trouble. Thanks again.

**Comment by cades** [comment]
Thanks @jamesob , the homebrew formula is working, but I noticed `desk version` now prints 0.1.1, maybe we should same version number on github release?

**Comment by jamesob** [comment]
@cades luckily, someone filed a PR for fish, so I've merged that and tagged a new release that actually matches `desk --version`. Nice spot, thank you!

**Comment by jamesob** [comment]
@cades are you going to file a PR against https://github.com/Homebrew/homebrew?
