### ISSUE TITLE
Add Homebrew package

### ISSUE THREAD

**Issue by cmbankester** [jamesob/desk#44]
I have a Homebrew package submission going (see the PR here: https://github.com/Homebrew/homebrew/pull/46325).

Thought I'd create an issue here to let you guys know and discuss it, if need be.

Great project, @jamesob! I use it *constantly*.

**Comment by jamesob** [comment]
Awesome, thanks @cmbankester! Glad you're getting use out of the tool.

I'll update the README upon merge of https://github.com/Homebrew/homebrew/pull/46325.

**Comment by cmbankester** [comment]
Merged! Installing, now, is as easy as `brew update && brew install desk` (if you use Homebrew).

**Comment by jamesob** [comment]
Thanks, Christian! You're the man! Am currently off the grid, but will
update README on return.
