### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by MrMitch** [jamesob/desk#48]
I have installed desk from git and just pulled the latest version (0.3.2). Whenever i try to use `desk go <desk_name>`, i get the following error : 

```bash
mitch@mitchbox desk go dash
/home/mitch/bin/desk: line 105: : command not found
```

**Comment by jamesob** [comment]
Hey, @MrMitch, thanks for the report. Could you do me a favor and attach some additional information like which shell you're running (with version), operating system, etc.? I'm unable to reproduce on OS X and Linux in zsh.

**Comment by MrMitch** [comment]
I'm on Ubuntu 15.10, my shell is Bash and `~/.desk/desks` is a symlink to another folder. I've not set any `$DESK_*` related var in my `.bashrc` file, the only desk related line in it are the following : 

```bash
# Hook for desk activation
[ ! -z "$DESK_ENV" ] && source "$DESK_ENV"
source /home/mitch/bin/desk-src/shell_plugins/bash/desk
```

Hope this helps, feel free to ask anything more you might need.

**Comment by jamesob** [comment]
@MrMitch I'm curious: if you remove `"$@"` from the end of this line: https://github.com/jamesob/desk/blob/master/desk#L105, does that resolve the issue?

**Comment by MrMitch** [comment]
@jamesob no it doesn't, I still get the same message.

**Comment by jamesob** [comment]
Odd, okay. Two ideas:
- can you add `echo $SHELL_EXEC` to the line above to see what desk is actually trying to execute, and
- can you use `git bisect` to find the commit that introduced this issue?

In the meantime, I'll try to recreate.

**Comment by MrMitch** [comment]
mitch@mitchbox [(09fdbe4...)|BISECTING] git bisect good
803bf37847633e2f685a46a27b11facf22efebec is the first bad commit

**Comment by MrMitch** [comment]
803bf37847633e2f685a46a27b11facf22efebec has two parents, 15919e99ded03c6ceea9ff98558e77a322a4dadb which is fine and 09fdbe4612066cf63ea46aee43c7cfaaff02ecfb which is also fine

**Comment by MrMitch** [comment]
adding `echo $SHELL_EXEC` prints a new empty line. It seems `get_running_shell` has trouble detecting the shell I use. FYI, `echo $SHELL` prints `/bin/bash`

**Comment by MrMitch** [comment]
strange thing : I'm using [Guake](https://github.com/Guake/guake) (0.7.2) as terminal. I went and tried `desk` in Gnome Terminal and it **works fine**!

**Comment by MrMitch** [comment]
complementary issue guake/issues#677 filed

**Comment by jamesob** [comment]
Interesting... thanks for the opening the Guake issue. Happy to modify https://github.com/jamesob/desk/commit/803bf37847633e2f685a46a27b11facf22efebec#diff-b506e098cf253ce028b8ba0a5fc7d473R167 to get this to work for Guake.

**Comment by MrMitch** [comment]
can this be a source of insight as to what is going on ? http://bash.cyberciti.biz/guide/$$

**Comment by MrMitch** [comment]
looking at the [get_running_shell](https://github.com/jamesob/desk/blob/master/desk#L257) function, it seems that `$CMDLINE_FILE` points to a file which content is `-`, so because of the `-e 's/^-//'` part on [line 257](https://github.com/jamesob/desk/blob/master/desk#L257), `$CMDLINE_SHELL` is empty, which is why `get_running_shell` returns an empty value, causing the `command not found` message.

**Comment by ericksonjoseph** [comment]
Hey I found an issue related to this one. get_running_shell was returning 3182. Im using bash on OSX

**Comment by drobati** [comment]
I came across this issue with `hyper.app` as a terminal. It worked fine in `terminal.app` for me.
