### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by cmbankester** [jamesob/desk#49]
I'd like to get [Desk's Homebrew distribution](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/desk.rb) updated with the recent feature additions. Could we tag master with `v0.4.0` (feature additions => minor version bump) soon?

**Comment by jamesob** [comment]
Right on, was going to do this today. Thanks, @cmbankester!

**Comment by cmbankester** [comment]
I have a PR going: https://github.com/Homebrew/homebrew/pull/47025
