### ISSUE TITLE
Display description of exported environment variables along with aliases and functions

### ISSUE THREAD

**Issue by rafaelbco** [jamesob/desk#56]
I think it would be useful if I could do something like that in a desk file:

```
# Description: my desk to work on things.

# Do something.
alias mycommand="foo"

# My environment variable.
export MYVAR="something"
```

And then when typing desk with the desk activated it would show the description of $MYVAR:

```
mydesk - my desk to work on things.

  mycommand  Do something.

Environment variables:

$MYVAR  My environment variable.
```

**Comment by cfont** [comment]
@jamesob, would you like me to create a PR related to this so you can check it out and determine if it indeed fixes this issue the way you would want?
