### ISSUE TITLE
Mr. jamesob, please fix your "desk" program.

### ISSUE THREAD

**Issue by hobbeswalsh** [jamesob/desk#59]
```
➤ desk init
Where do you want to store your deskfiles? (default: /Users/robin/.desk): /Users/robin/.config/desk
/Users/robin/.config/desk doesn't exist, attempting to create.
Where's your shell rc file? (default: /Users/robin/.config/fish/config.fish):
Done. Start adding desks to /Users/robin/.config/desk/desks!

➤ desk
No desk activated.

No desk dir! Run 'desk init'.⏎
```

What??? But I just initialized a desk dir!

**Comment by hobbeswalsh** [comment]
'nuff said!

**Comment by jamesob** [comment]
Ah yeah, you've definitely found a usability bummer. Check [this](https://github.com/jamesob/desk#using-a-non-default-config-location) part of the README out -- though we should definitely make some improvements to the code to account for this.

**Comment by hobbeswalsh** [comment]
Ok, yes, but I still have one outstanding question.

You write:

```
ensure you set $DESK_DIR and/or $DESK_DESKS_DIR to match in your shell's rc file.
```

I think it would be a useful feature to be able to continue along this logical path and arbitrarily nest the string `_DESKS`.

For example, I should be able to set the following environment variable:

`$DESK_DESKS_DESKS_DESKS_DIR`

I should also be able to set the following environment variable:

`$DESK_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DESKS_DIR`

**Comment by jamesob** [comment]
Usability/arbitrary-nesting-of-`DESK` still a problem; keeping this baby open.
