### ISSUE TITLE
Desk release v0.5.0

### ISSUE THREAD

**Issue by raypatterson** [jamesob/desk#63]
HI,

Thanks for creating Desk! I have installed via Homebrew and as v0.5.0 has not been released, I cannot upgrade via that channel. Any plans to release this update?

Thanks again!

**Comment by jamesob** [comment]
Thanks for the report, Ray. I'll do some testing and cut a release later today.

**Comment by raypatterson** [comment]
Wow! Much appreciated!

**Comment by jamesob** [comment]
@raypatterson sorry for the delay. I've cut [a release](https://github.com/jamesob/desk/releases/tag/v0.5.0) though I'm not sure if that propagates to Homebrew somehow... let me know if not. 

Thanks!

**Comment by raypatterson** [comment]
I was able to update the formula manually and will make a pull request of Homebrew if no one else does soon 👍  thanks again!

**Comment by jamesob** [comment]
Thank *you* for filing, Ray!
