### ISSUE TITLE
#62 broke desk within tmux

### ISSUE THREAD

**Issue by KevinSjoberg** [jamesob/desk#64]
#62 broke desk when used within tmux. Running `desk . <deskname>` outside tmux works as expected. Running `desk . <deskname>` within tmux errors out with the following message:

    /usr/local/bin/desk: line 133: 4744: command not found

**Comment by jamesob** [comment]
Thanks for the report! This should be fixed in release 0.5.1: https://github.com/jamesob/desk/releases/tag/v0.5.1

Feel free to reopen if not.
