### ISSUE TITLE
Functions Printing Ugly

### ISSUE THREAD

**Issue by paulmolluzzo** [jamesob/desk#7]
Using desk on OSX 10.10 (bash) the layout of the output from the `desk` command inside a desk doesn't match the gif in the README. Instead of just the name of the function and the description like `foo - description of foo` I get the parentheses after the name and then also get a new line with an opening curly brace. Using the `plan` function from one of your examples, I get this:

```
plan() - Run `terraform plan` with proper AWS var config
  {
```

Any thoughts on if this is a local issue or part of the project?

**Comment by jamesob** [comment]
Thanks for filling, Paul. I think the issue here is probably a difference in the behavior of `grep -E` on your machine and mine, which manifests [here](https://github.com/jamesob/desk/blob/master/desk#L137-L139). 

Can you send me over your `grep --version`? I've got an OS X machine I can test on tonight at home.

Thanks again for filing.

**Comment by paulmolluzzo** [comment]
grep (BSD grep) 2.5.1-FreeBSD

My first guess with that it's a difference in `sed`, so you may be on to something.

**Comment by iammer** [comment]
I ran into this as well, had to do brew install gnu-sed and then change desk to use gsed.

**Comment by jamesob** [comment]
I can work on this in the PST evening, but if either of you would like to PR a fix in the meantime...

Maybe we could conditionalize `get_callables` based on the installed `sed` version? There's gotta be an incantation of sed that'll work with OS X's out-of-the-box version.

**Comment by paulmolluzzo** [comment]
It's the flags and the versions, but I don't know how you'd "switch" on the version. You can see a similar discussion of the differences between versions of `sed` in this discussion: https://github.com/paulirish/dotfiles/commit/6743b907ff586c28cd36e08d1e1c634e2968893e#commitcomment-13349456

I think the issue is really Yosemite.

**Comment by jamesob** [comment]
@paulmolluzzo I've merged @iammer's fix; mind pulling `master` and giving it a go?

**Comment by paulmolluzzo** [comment]
Yeah, probably a couple hours out but I'll definitely update and test it. Thanks!

**Comment by paulmolluzzo** [comment]
Works here. Thanks @iammer!
