### ISSUE TITLE
desk installed from homebrew only lauches shell, doesn't execute deskfile

### ISSUE THREAD

**Issue by MrMitch** [jamesob/desk#70]
I installed desk 0.6.0 from homebrew on OS X El Capitan. I use a custom DESK_DESKS_DIR (`DESK_DESKS_DIR=~/Workspace/desks`).

When I try to start a desk, the following happens : 
![image](https://cloud.githubusercontent.com/assets/576772/16533417/d8d66a72-3fd8-11e6-9da6-a37cb5cb5322.png)

**Comment by MrMitch** [comment]
The `mafiesta.sh` desk file exists in my desk desks dir :
![image](https://cloud.githubusercontent.com/assets/576772/16533495/526a0b5a-3fd9-11e6-9e43-4d63d9ec9b20.png)

**Comment by angusb** [comment]
@MrMitch did you ever resolve this? I've run into the same issue. Manual installation doesn't seem to work either. I'm using oh-my-zsh

**Comment by MrMitch** [comment]
nope, I never did. cc @jamesob

**Comment by McKean** [comment]
@MrMitch can you show the contents of mafiesta? Also, did you follow: https://github.com/jamesob/desk#usage-with-os-x

**Comment by MrMitch** [comment]
@McKean yes, i followed the instructions. I no longer use a Mac so i'm closing this for now.

**Comment by yonglam** [comment]
I've run into the same issue. Finally fixed it by deleting the `desks_dir` and ran `desk init` to recreate it. 
Because I created `desks_dir` manually, `[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true` was not appended to my `.zshrc` file. That's the cause.
