### ISSUE TITLE
I ❤️ DESK!

### ISSUE THREAD

**Issue by hamin** [jamesob/desk#77]
This isn't really an issue but more of a thank you @jamesob! I've been using desk for the past 2 years now mainly to manage env vars for different workspaces (among other things) across a polyglot development environment. 

I really really love this tool. I love it so much that i have over 52 desk files on my work machine! 

I'm a constant advocate to the other members on my team and have been able to convince at least some of them to try (all of whom have loved it). 

I'd like to share a tool that I created to solve my own itch for managing my 50+ desk workspaces https://github.com/hamin/godesk . It's a dead simple, quickly hacked together launcher w/ fuzzy filtering that's been making my life easier and hopefully others here and yourself @jamesob will find it to be too :) . Here's a GIF of it in action

![GIF](https://raw.githubusercontent.com/hamin/godesk/master/demo.gif)

Please feel free to close this issue at your will :)

Hope you enjoy it to... and again... thank you!!!! ❤️

**Comment by jamesob** [comment]
Aw thanks, @hamin! Really warms the 'ol heart to know that other people are getting use out of this tool. I'll throw up a link to your project in the README.

You also might want to check out [fzf](https://github.com/junegunn/fzf), which is a really nice project and (I think) is extensible.

**Comment by hamin** [comment]
❤️
