### ISSUE TITLE
is there a way to start new terminal session with previous used desk session?

### ISSUE THREAD

**Issue by McKean** [jamesob/desk#79]
When I switch to a desk and then create a new terminal window, eg urxvt, I would love to have this use the same desk. This could be similarly accomplished as we do it with resuming on the same path.

I'm just wondering if anyone is doing this already and could point me in the right direction.

What would also be interesting is to start urxvt in a specific desk mode.

thanks!

**Comment by partounian** [comment]
Maybe tmux?

**Comment by McKean** [comment]
Using direnv in favor of desk these days.
